config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :uploads

  get '/:id' => "shortener/shortened_urls#show"

  root to: 'uploads#new', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/referenceable.rb
module Referenceable
  extend ActiveSupport::Concern

  included do
    before_validation :set_reference, on: :create
  end

  # Sets a short, unique reference ID
  def set_reference
    self.reference = loop do
      ref = SecureRandom.hex(3)
      break ref unless self.class.exists?(reference: ref)
    end
  end
end

app/models/upload.rb
class Upload < ApplicationRecord
  include Referenceable
  include Rails.application.routes.url_helpers

  has_many_attached :files

  belongs_to :user

  validates :reference, uniqueness: { case_sensitive: true }
  before_create :set_upload_share_link
  before_validation :sanitize_list

  private

  def set_upload_share_link
    self.link = uploads_url(self, only_path: false, host: ENV.fetch('APPLICATION_HOST'))
  end

  def sanitize_list
    return if files.size < 2

    # get all uploads with files for current user
    Upload.with_attached_files
          .where(user_id: user.id)
          .each do |upload|
            upload.files.each do |file|
              # add them to the current list of file to be uploaded
              files << file
            end
          end

    file_set = {}

    files.each do |file|
      check = file.blob.checksum

      file.purge if file_set[check].present?

      file_set[check] = file.blob
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :uploads

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # TODO: implement authentication
  # before_action :authenticate_user!
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: %i[show edit update]
  before_action :confirm_files_attached, only: %i[create]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = [].tap do |files|
      Upload.with_attached_files
            .where(user_id: current_or_guest_user.id)
            .each do |upload|
              upload.files.each do |file|
                files << { id: upload.id, file: file }
              end
            end
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
    @uploads = [].tap do |files|
      Upload.with_attached_files
            .where(user_id: current_or_guest_user.id)
            .each do |upload|
              upload.files.each do |file|
                files << { id: upload.id, file: file }
              end
            end
    end
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    new_uploads = create_upload_params
    new_uploads[:user_id] = current_or_guest_user.id

    @upload = Upload.new(new_uploads)

    if @upload.save
      flash[:success] = 'File Upload Successfully!'
    else
      flash[:danger] = 'An error occurred. Please try again!'
      flash[:error] = t(@upload.errors.full_messages.to_sentence)
    end
    redirect_to root_path
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = @upload = Upload.find_by(id: params[:id], user_id: current_or_guest_user.id)
    @file = ActiveStorage::Attachment.find(params[:file])
    @file&.purge
    @upload.destroy unless @upload.files.present?
    flash[:success] = 'File Deleted Successful!'
    redirect_to root_path
  rescue StandardError => error
    flash[:danger] = 'File Does Not Exist!'
    flash[:error] = error.message
    redirect_to root_path
  end

  private

  def set_upload
    @upload = Upload.find(params[:id] || params[:upload_id])
  end

  def upload_params
    params.require(:upload).permit(:link, :archived)
  end

  def create_upload_params
    params.require(:upload).permit(files: [])
  end

  def confirm_files_attached
    return if create_upload_params[:files].present?
    redirect_to new_upload_path
    flash[:warning] = 'No Files Attached For Upload!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nofile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta name="theme-color" content="#285b8e" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://unpkg.com/ionicons@4.4.7/dist/css/ionicons.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <% unless flash.empty? %>
      <% flash.each do |f| %>
        <% type = f[0].to_s %>
        <% message = f[1].to_s %>
        <%= flash_toastr %>
      <% end %>
    <% end %>

    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
      <p>Blog | About | FAQ | Contact</p>
      <p>©<%= Time.now.year %> Nofile.ng. All Rights Reserved</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container">
    <%= link_to 'NoFile.ng', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to root_path, class: 'nav-link' do %>
            New Upload
            <span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(uploads_path) %>">
          <%= link_to 'View All Uploads', uploads_path, class: 'nav-link' %>
        </li>
      </ul>
      <%= link_to 'Contribute', 'https://github.com/jattoabdul/nofile-clone', class: 'navbar-action-call my-2 my-md-0' %>
    </div>
  </div>
</nav>

app/views/uploads/_form.html.erb
<%= form_with model: upload, class: 'upload-form' do |form| %>
  <div class="form-container">
    <div class="field">
      <%= form.file_field :files, multiple: true, direct_upload: true, required: true %>
      <%= form.label :files, '', class: 'form-label' do %>
        <span><i class="icon ion-ios-cloud-upload"></i> click here to select files</span>
      <% end %>
    </div>
    <div class="actions">
      <%= form.button :submit, class: "btn upload-btn" do %>
        <i class='icon ion-ios-cloud-upload'></i> Upload
      <% end %>
    </div>
  </div>
  <div id="selected-files"></div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div class="all-uploads-container">
  <section class="header-section" id="header-section">
    <div class="container all-uploads-wrapper">
      <% unless @uploads.empty? %>
        <div class="all-uploads">
          <h3>All Uploaded Files</h3>
          <% @uploads.each do |upload| %>
            <div class="upload_file_item">
              <div class="top">
                <p class="file_description_action">
                  <span><i class='icon ion-ios-document'></i> <%= upload[:file].filename %></span> | 
                  <span><%= link_to "Delete", upload_path(id: upload[:id], file: upload[:file]), method: :delete, class: "icon ion-ios-trash" %></span>
                  <span class="completed"><i class='icon ion-ios-cloud-done'></i> Completed</span>
                </p>
              </div>
              <div class="bottom">
                <p class="file_link" id="file_link">
                    <%= short_url(rails_blob_url(upload[:file])) %>
                </p>
                <p class="file_action copy_link" data-clipboard-action="copy" data-clipboard-target="#file_link">
                  <i class='icon ion-ios-copy'></i>
                </p>
                <p class="file_action download">
                  <%= link_to '', rails_blob_path(upload[:file], disposition: 'attachment'), class: "icon ion-ios-cloud-download" %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <h3 class="no-files">No uploaded files</h3>
      <% end %>
    </div>
  </section>
</div>

app/views/uploads/new.html.erb
<div class="main-container">
  <section class="header-section" id="header-section">
    <div class="container new-upload-wrapper">
      <%= render 'form', upload: @upload %>

      <% unless @uploads.empty? %>
      <div class="uploaded-files">

        <% @uploads.each do |upload| %>
          <div class="upload_file_item">
            <div class="top">
              <p class="file_description_action">
                <span><i class='icon ion-ios-document'></i> <%= upload[:file].filename %></span> | 
                <span><%= link_to "Delete", upload_path(id: upload[:id], file: upload[:file]), method: :delete, class: "icon ion-ios-trash" %></span>
                <span class="completed"><i class='icon ion-ios-cloud-done'></i> Completed</span>
              </p>
            </div>
            <div class="bottom">
              <p class="file_link" id="file_link">
                  <%= short_url(rails_blob_url(upload[:file])) %>
              </p>
              <p class="file_action copy_link" data-clipboard-action="copy" data-clipboard-target="#file_link">
                <i class='icon ion-ios-copy'></i>
              </p>
              <p class="file_action download">
                <%= link_to '', rails_blob_path(upload[:file], disposition: 'attachment'), class: "icon ion-ios-cloud-download" %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
        <h3 class="no-files">No uploaded files</h3>
      <% end %>
    </div>
  </section>
</div>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @upload.link %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @upload.reference %>
</p>

<p>
  <strong>Archived:</strong>
  <%= @upload.archived %>
</p>

<p>
  <strong>User:</strong>
  <%= @upload.user %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>